name: Release
on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build
        run: docker build -t dbt-ai-deployer .
        env:
          DOCKER_BUILDKIT: 1

      # Use the image from build-and-push step
      - name: Publish to PyPI
        run: |
          docker run --rm -e PYPI_USERNAME='__token__' -e PYPI_PASSWORD_TEST='${{ secrets.PYPI_PASSWORD_TEST }}' dbt-ai-deployer make publish-test

