name: Release
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install GitHub CLI
        run: |
          type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
          && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ github.sha }}
      - name: Update package name
        run: |
          PACKAGE_NAME=dbt-ai-deployer
          gh container package update ${{ github.repository }}:${{ github.sha }} --name "$PACKAGE_NAME" --private


#  publish:
#   name: Publish to PyPI
#    runs-on: ubuntu-latest
#    steps:
#    - name: Checkout code
#      uses: actions/checkout@v2
#    - name: Build Docker image
#      run: docker build -t my-image-name .
#    - name: Bump version
#      uses: marvinpinto/action-automatic-semantic-version@v1
#      with:
#        repo_token: ${{ secrets.GITHUB_TOKEN }}
#    - name: Publish to PyPI
#      run: docker run --rm -v $PWD:/app my-image-name make publish-prod
#      env:
#        PYPI_USERNAME: __token__
#        PYPI_PASSWORD_PROD: ${{ secrets.PYPI_API_TOKEN }}
